### ISSUE TITLE
forgot password works sometimes and doesn't work the other times

### ISSUE THREAD

**Issue by Mg1414** [Naman-K-Jaiswal/ConnVerse#25]

**Comment by Jenil-Dobariya** [comment]
If some feature is not working at only some time, It doesn't mean that there is an bug in the code. It can also happen due to some other factors like, bad network connection.

When there is a bug in the code, the bug arrives after certain steps taken by the user. So please provide those steps otherwise we will force to assume that issue was due to other factors and close the issue.

**Comment by PKING1501** [comment]
Done
